# Data Preparation

1) Pengumpulan Data

In [1]:
# Import Libraries

# Mengimpor library dasar
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Load Dataset

# Mengimpor dataset dari penyimpanan internal 
data_set = 'bahan/final bahan/mergeFile-en new.csv'
df = pd.read_csv(data_set, encoding='utf-8', sep=';')

2) Penanganan Data yang Hilang

In [3]:
# Menggunakan isnull() dan sum()
missing_count = df["descriptions"].isnull().sum()
print(f"Jumlah missing value dalam kolom 'descriptions': {missing_count}")

Jumlah missing value dalam kolom 'descriptions': 107

In [4]:
# Menampilkan baris dengan missing value
rows_with_missing = df[df["descriptions"].isnull()]
print("\nBaris dengan missing value dalam kolom 'desccriptions':")
print(rows_with_missing)

Baris dengan missing value dalam kolom 'desccriptions':
                             job_title  \
20                   Engineering Staff
44                Senior Web Developer
47         Web Developer (WIX) and SEO
54                   Software Engineer
58         Back end developer / Devops
...                                ...
2258                   Systems Analyst
2288  GA System Apps. Engineer, IT, SS
2290                   Systems Analyst
2320  GA System Apps. Engineer, IT, SS
2322                   Systems Analyst

                                      company descriptions  \
20                     PT PRIMA PRESISI ABADI          NaN
44                    PT Monitor News Sources          NaN
47               PT Petrolindo Energi Perkasa          NaN
54            PT Tigernix Solutions Indonesia          NaN
58                    PT CahayaThanks Perfect          NaN
...                                       ...          ...
2258  PT Mulia Cemerlang Abadi Multi Industry          NaN
2288                         PT RGE Indonesia          NaN
2290  PT Mulia Cemerlang Abadi Multi Industry          NaN
2320                         PT RGE Indonesia          NaN
2322  PT Mulia Cemerlang Abadi Multi Industry          NaN

                      location                   subcategory           type  \
20         Karawang, West Java        Engineering - Software      full time
44      South Jakarta, Jakarta  Web Development & Production      full time
47      North Jakarta, Jakarta          Developer/Programmer  Contract/Temp
54    Batam City, Riau Islands          Developer/Programmer  Contract/Temp
58    Central Jakarta, Jakarta          Developer/Programmer      full time
...                        ...                           ...            ...
2258                  Sukabumi       Business/System Analyst      full time
2288         Bangkalan Regency       Business/System Analyst      full time
2290                  Sukabumi       Business/System Analyst      full time
2320         Bangkalan Regency       Business/System Analyst      full time
2322                  Sukabumi       Business/System Analyst      full time

                                       salary date_ingestion
20    IDR 5,000,000 â€“ IDR 7,000,000 per month     16/01/2024
44                                        NaN     16/01/2024
47                                        NaN     16/01/2024
54                                        NaN     16/01/2024
58                                        NaN     16/01/2024
...                                       ...            ...
2258                                      NaN     27/06/2024
2288                                      NaN     27/06/2024
2290                                      NaN     27/06/2024
2320                                      NaN     27/06/2024
2322                                      NaN     27/06/2024

[107 rows x 8 columns]

In [5]:
# Menghapus baris yang mengandung missing values
df["descriptions"] = df["descriptions"].dropna()

3) Penanganan Outlier

In [6]:
# Analisis Panjang String
df['string_length'] = df['descriptions'].str.len()
length_mean = df['string_length'].mean()
length_std = df['string_length'].std()
length_outliers = df[(df['string_length'] > length_mean + 2*length_std) | 
                     (df['string_length'] < length_mean - 2*length_std)]

print("Outliers berdasarkan panjang string:")
print(length_outliers[['descriptions', 'string_length']])

Outliers berdasarkan panjang string:
                                           descriptions  string_length
3     Minimum working experience 2 years; Passion fo...         3266.0
9     Mastering one of the programming languages; Ma...         3668.0
138   Define and establish the end to end operation ...         3565.0
212   Manage work within the SOC scope and be respon...         2614.0
257   Apply emerging technologies to help our client...         2954.0
...                                                 ...            ...
2259  Performs analysis and makes recommendations in...         2801.0
2278  Project Management Experience\n: Strong projec...         2738.0
2291  Performs analysis and makes recommendations in...         2801.0
2310  Project Management Experience\n: Strong projec...         2738.0
2323  Performs analysis and makes recommendations in...         2801.0

[111 rows x 2 columns]

In [7]:
# Analisis Frekuensi Kata
def word_count(text):
    return len(str(text).split())

df['word_count'] = df['descriptions'].apply(word_count)
word_count_mean = df['word_count'].mean()
word_count_std = df['word_count'].std()
word_count_outliers = df[(df['word_count'] > word_count_mean + 2*word_count_std) | 
                         (df['word_count'] < word_count_mean - 2*word_count_std)]

print("\nOutliers berdasarkan jumlah kata:")
print(word_count_outliers[['descriptions', 'word_count']])

Outliers berdasarkan jumlah kata:
                                           descriptions  word_count
3     Minimum working experience 2 years; Passion fo...         463
9     Mastering one of the programming languages; Ma...         512
138   Define and establish the end to end operation ...         508
212   Manage work within the SOC scope and be respon...         353
241   Who handles technical duties, focused on selli...         369
...                                                 ...         ...
2195  Performs analysis and makes recommendations in...         377
2227  Performs analysis and makes recommendations in...         377
2259  Performs analysis and makes recommendations in...         377
2291  Performs analysis and makes recommendations in...         377
2323  Performs analysis and makes recommendations in...         377

[82 rows x 2 columns]

In [8]:
# Analisis Kata Unik
def unique_word_ratio(text):
    words = str(text).lower().split()
    return len(set(words)) / len(words) if len(words) > 0 else 0

df['unique_word_ratio'] = df['descriptions'].apply(unique_word_ratio)
unique_ratio_mean = df['unique_word_ratio'].mean()
unique_ratio_std = df['unique_word_ratio'].std()
unique_ratio_outliers = df[(df['unique_word_ratio'] > unique_ratio_mean + 2*unique_ratio_std) | 
                           (df['unique_word_ratio'] < unique_ratio_mean - 2*unique_ratio_std)]

print("\nOutliers berdasarkan rasio kata unik:")
print(unique_ratio_outliers[['descriptions', 'unique_word_ratio']])

Outliers berdasarkan rasio kata unik:
                                          descriptions  unique_word_ratio
3    Minimum working experience 2 years; Passion fo...           0.466523
21   Support for Setting Promotion on Invoices; Val...           0.389831
22   Education: Diploma or Bachelor's degree in Com...           0.431373
23   Maximum age 35 years. Minimum education: Bache...           0.459259
33   Minimum Bachelor's Degree in Information Techn...           0.430556
75   Vocational school/Diploma/Bachelor's degree in...           0.435897
102  Work in all phases of front-end and back-end d...           0.466321
138  Define and establish the end to end operation ...           0.490157

In [9]:
df

,job_title,company,descriptions,location,subcategory,type,salary,date_ingestion,string_length,word_count,unique_word_ratio
0,Microsoft Dynamics / Power Apps Developer,PT Xumei Food Tech Indonesia,"Bachelor's degree in computer science, enginee...","West Jakarta, Jakarta",Developer/Programmer,full time,NaN,16/01/2024,1296.0,181,0.679558
1,Frontend Internship,PT. Radha Mustika Chakra,Develop new user interface features that meet ...,Jakarta,Engineering - Software,Casual/Vacation,NaN,16/01/2024,931.0,138,0.797101
2,Fullstack Engineer,PT Teknologi Pamadya Analytical,Deeply engaged in the full development lifecyc...,"Tangerang, Banten",Developer/Programmer,full time,NaN,16/01/2024,2395.0,318,0.694969
3,Web Developer,PT Supra Boga Lestari Tbk,Minimum working experience 2 years; Passion fo...,Jakarta,Engineering - Software,full time,NaN,16/01/2024,3266.0,463,0.466523
4,Senior Python IT Staff,PT. Sinar Mas Insurance,"Male/Female, max age 28 years; Bachelor's degr...","Central Jakarta, Jakarta",Engineering - Software,full time,NaN,16/01/2024,344.0,49,0.938776
...,...,...,...,...,...,...,...,...,...,...,...
2335,SYSTEM SUPPORT,PT Asuransi Harta Aman Pratama Tbk,\nRole descriptions Salary insights Tools to h...,Greater Jakarta,Network & System Administration,full time,NaN,27/06/2024,70.0,11,1.000000
2336,Senior Systems Analyst,PT. K-LINK INDONESIA,What's your expected monthly basic salary? How...,South Jakarta,Business/System Analyst,full time,"IDR 10,000,000 â€“ IDR 14,000,000 per month",27/06/2024,232.0,37,0.783784
2337,Inspur IT Server Engineer,TITANICOM TECH LIMITED,Coordinating with team members in order to ide...,Greater Jakarta,Engineering - Hardware,full time,"IDR 13,000,000 â€“ IDR 14,000,000 per month",27/06/2024,2118.0,287,0.679443
2338,IT System Administration and General Affairs -...,PT Tri Dharma Protection,What's your expected monthly basic salary? Whi...,South Jakarta,Network & System Administration,full time,NaN,27/06/2024,593.0,97,0.546392
2339,Information Security and System Risk Controlle...,PT Bank Resona Perdania,"To do risk identification, measurement, monito...",Central Jakarta,Security,full time,NaN,27/06/2024,1661.0,238,0.663866

4) Konversi Tipe Data

In [10]:
df["descriptions"] = df["descriptions"].astype(str)

Pemilihan Dataframe Sementara

In [11]:
# Memilih fitur dan label proses
df_process = df[['descriptions', 'subcategory', 'string_length', 'word_count', 'unique_word_ratio']]
df_process

,descriptions,subcategory,string_length,word_count,unique_word_ratio
0,"Bachelor's degree in computer science, enginee...",Developer/Programmer,1296.0,181,0.679558
1,Develop new user interface features that meet ...,Engineering - Software,931.0,138,0.797101
2,Deeply engaged in the full development lifecyc...,Developer/Programmer,2395.0,318,0.694969
3,Minimum working experience 2 years; Passion fo...,Engineering - Software,3266.0,463,0.466523
4,"Male/Female, max age 28 years; Bachelor's degr...",Engineering - Software,344.0,49,0.938776
...,...,...,...,...,...
2335,\nRole descriptions Salary insights Tools to h...,Network & System Administration,70.0,11,1.000000
2336,What's your expected monthly basic salary? How...,Business/System Analyst,232.0,37,0.783784
2337,Coordinating with team members in order to ide...,Engineering - Hardware,2118.0,287,0.679443
2338,What's your expected monthly basic salary? Whi...,Network & System Administration,593.0,97,0.546392
2339,"To do risk identification, measurement, monito...",Security,1661.0,238,0.663866

5) Pembersihan Data

In [12]:
import re

# Fungsi untuk membersihkan teks
def clean_text(text):
    if isinstance(text, str):
        text = re.sub(r'\d+', '', text)  # Menghapus angka
        text = re.sub(r'[^\w\s]', '', text)  # Menghapus tanda baca dan karakter khusus kecuali spasi
        text = re.sub(r'\W', ' ', text)  # Menghapus karakter non-alphanumeric
        text = re.sub(r'\s+', ' ', text)  # Menghapus spasi berlebih
        text = text.lower()  # Mengubah teks menjadi huruf kecil
        return text
    else:
        return ''  # Kembalikan string kosong jika bukan string
    
# Contoh penerapan fungsi clean_text pada kolom 'descriptions'
df_process['descriptions'] = df_process['descriptions'].apply(clean_text)
df_process

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,descriptions,subcategory,string_length,word_count,unique_word_ratio
0,bachelors degree in computer science engineeri...,Developer/Programmer,1296.0,181,0.679558
1,develop new user interface features that meet ...,Engineering - Software,931.0,138,0.797101
2,deeply engaged in the full development lifecyc...,Developer/Programmer,2395.0,318,0.694969
3,minimum working experience years passion for p...,Engineering - Software,3266.0,463,0.466523
4,malefemale max age years bachelors degree in i...,Engineering - Software,344.0,49,0.938776
...,...,...,...,...,...
2335,role descriptions salary insights tools to he...,Network & System Administration,70.0,11,1.000000
2336,whats your expected monthly basic salary how m...,Business/System Analyst,232.0,37,0.783784
2337,coordinating with team members in order to ide...,Engineering - Hardware,2118.0,287,0.679443
2338,whats your expected monthly basic salary which...,Network & System Administration,593.0,97,0.546392
2339,to do risk identification measurement monitori...,Security,1661.0,238,0.663866

6) Stopword removal

In [13]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS

# Model Pemrosesan Bahasa dengan spaCy
nlp = spacy.load("en_core_web_sm")
docs = list(nlp.pipe(df_process['descriptions']))

# Membaca daftar stopword dari file eksternal
with open('bahan/selected_stopwords.txt', 'r') as file:
    external_stopwords = set(file.read().splitlines())  # Menggunakan set untuk performa lebih baik

# Tampilkan daftar stopword yang dibaca
print(external_stopwords)

# Definisi fungsi untuk tokenisasi, penghapusan stop words, huruf asing, dan lemmatization
def preprocess_text(text):
    doc = nlp(text)
    
    # Proses tokenisasi, lemmatization, penghapusan stop words, huruf asing, dan stop words eksternal
    tokens = [
        token.lemma_.strip() for token in doc 
        if not token.is_stop                      # Hapus stop words dari spaCy
        and len(token.lemma_) > 1                 # Hapus token yang hanya 1 karakter
        and token.text.lower() not in STOP_WORDS  # Hapus stop words default dari spaCy
        and token.text.lower() not in external_stopwords  # Hapus stop words dari file eksternal
        and not (len(token.text) == 1 and token.is_alpha) # Hapus huruf asing yang berdiri sendiri
    ]
    
    return tokens

# Contoh penggunaan pada kolom descriptions
df_process['result_descriptions'] = df_process['descriptions'].apply(preprocess_text)

# Fungsi untuk menghapus stopword yang tersisa setelah preprocessing
def remove_stopwords(text, stopwords):
    if not isinstance(text, str):
        text = str(text)  # Mengonversi nilai non-string menjadi string
    words = text.split()
    cleaned_text = ' '.join([word for word in words if word.lower() not in stopwords])
    return cleaned_text

# Terapkan fungsi remove_stopwords pada kolom 'result_descriptions' (bisa dipakai jika diperlukan setelah lemmatization)
df_process['result_descriptions'] = df_process['result_descriptions'].apply(lambda x: remove_stopwords(' '.join(x), external_stopwords))

{'', 'karawaci', 'stun', 'expense', 'contractual', 'completeness', 'mindset', 'adjustment', 'health', 'interesting', 'simulation', 'project', 'judgment', 'rau', 'panel', 'remark', 'efficiently', 'display', 'committed', 'name', 'mathematicsphysicstelecommunication', 'liaise', 'adhoc', 'super', 'multidisciplinary', 'mainly', 'javascripttypescript', 'interchange', 'protect', 'ecommerce', 'reading', 'undergo', 'demonstrate', 'custodian', 'nd', 'crimping', 'culture', 'er', 'eagerness', 'deftly', 'tv', 'methodologie', 'spoken', 'assemble', 'wife', 'add', 'semarang', 'preferred', 'crossfuntional', 'modern', 'free', 'optimize', 'willing', 'paloalto', 'administer', 'confidently', 'normal', 'host', 'avoid', 'py', 'incld', 'assessment', 'craft', 'voip', 'packing', 'collaboration', 'orchestration', 'yarn', 'synthesis', 'involve', 'session', 'solver', 'mastery', 'element', 'active', 'aspmvc', 'pronunciation', 'question', 'encourage', 'upper', 'milestone', 'agent', 'archive', 'fastmove', 'exercise', 'field', 'reprioritize', 'elk', 'mentally', 'happen', 'computertelecommunication', 'setup', 'consideredexperience', 'highquality', 'speed', 'distributor', 'welldesigne', 'klypco', 'legal', 'ethical', 'accustom', 'bogor', 'human', 'webinar', 'highscale', 'immediately', 'asset', 'reduction', 'draft', 'big', 'remotely', 'buying', 'downtoearth', 'salemba', 'caspnetjavascriptjavascript', 'measuer', 'correctly', 'settle', 'kdp', 'close', 'impact', 'coordination', 'prepare', 'transactional', 'ssa', 'challenge', 'current', 'benchmark', 'microservice', 'abnormal', 'principle', 'bdc', 'importance', 'toolslibrary', 'effectiveness', 'phone', 'intensively', 'procurerepair', 'distribution', 'north', 'actual', 'thing', 'town', 'raise', 'manager', 'clinical', 'out', 'thirdparty', 'balance', 'io', 'node', 'page', 'cause', 'privilege', 'specify', 'applicationsprogram', 'improve', 'intrusion', 'activedirectory', 'securityrelate', 'approve', 'etraine', 'tend', 'ojk', 'cit', 'intensely', 'mimic', 'inside', 'personalization', 'identity', 'convention', 'help', 'concurrent', 'creativity', 'routine', 'adaptability', 'csa', 'smartform', 'crystal', 'carrying', 'sharepoint', 'pack', 'formulate', 'emergency', 'private', 'specialist', 'influx', 'esb', 'tech', 'boardroom', 'orient', 'verification', 'attack', 'landowner', 'identify', 'operate', 'end', 'interpret', 'schedule', 'market', 'redi', 'result', 'wellstructure', 'developmentdevop', 'disclosure', 'serveroracle', 'cpam', 'allowance', 'law', 'officer', 'ready', 'facility', 'pa', 'cluster', 'performable', 'implementation', 'crosscultural', 'procedurecisspcisacism', 'attachment', 'increase', 'relationship', 'updatetechnical', 'lso', 'autonomously', 'hybrid', 'academic', 'sudah', 'quick', 'potential', 'reactive', 'aesthetic', 'give', 'grow', 'convince', 'deadline', 'expose', 'tune', 'quality', 'playwright', 'white', 'agree', 'mis', 'message', 'fire', 'week', 'start', 'invoicing', 'high', 'leadershipmanagement', 'escalation', 'finding', 'assume', 'proposal', 'industry', 'dast', 'tanggerang', 'securely', 'month', 'hana', 'gather', 'ioh', 'commitment', 'cleanse', 'description', 'multiple', 'contact', 'gain', 'small', 'review', 'baq', 'selection', 'wellstructured', 'correct', 'virtual', 'pop', 'horizontally', 'studies', 'feel', 'surround', 'employment', 'language', 'externally', 'solman', 'cs', 'retrospective', 'collaborate', 'nature', 'assist', 'business', 'video', 'methodstechnology', 'chain', 'proceed', 'track', 'occur', 'analyzer', 'sound', 'sequence', 'resume', 'hypothesis', 'perform', 'jakarta', 'union', 'serverside', 'touchpoint', 'variety', 'lay', 'mock', 'occasional', 'presalessolution', 'document', 'japanese', 'enhance', 'value', 'datamine', 'thinking', 'family', 'robust', 'actionable', 'range', 'usage', 'regular', 'ax', 'limitation', 'suite', 'master', 'layer', 'consider', 'particular', 'salesforce', 'aptitude', 'editing', 'preparation', 'postimplementation', 'prince', 'travel document', 'modeling', 'financing', 'prevent', 'diplomabachelor', 'needs', 'require', 'ale', 'maturity', 'degradation', 'costumize', 'print', 'basicfluent', 'ado', 'anti', 'orchestrate', 'strategic', 'internshipinternship', 'conversion', 'cr', 'unitintegration', 'protection', 'saja', 'survey', 'product', 'transition', 'long', 'supervision', 'loyal', 'multitaske', 'thinker', 'sop', 'overseas', 'component', 'produce', 'wide', 'yogyakarta', 'userexit', 'responsibilitie', 'consensus', 'upload', 'breakout', 'link', 'turn', 'librarie', 'fill', 'impress', 'detection', 'hide', 'modules', 'redis', 'notify', 'discovery', 'mysqlpostgressql', 'al', 'british', 'vendor', 'equivalent', 'large', 'badung', 'recurrence', 'accessibility', 'code', 'targetdeadline', 'strength', 'trade', 'sharp', 'rework', 'calculate', 'property', 'min', 'map', 'accuracy', 'possible', 'ongoing', 'public', 'ad', 'proyek', 'test', 'personal', 'discipline', 'corrective', 'series', 'reinforce', 'cikokol', 'cover', 'lake', 'professionalism', 'inspire', 'basis', 'strict', 'campaign', 'headquarters', 'consult', 'way', 'container', 'mogot', 'inginkan', 'american', 'weakness', 'transforming', 'phase', 'qmap', 'restore', 'manner', 'apache', 'translate', 'smasmk', 'visionary', 'graduate', 'physically', 'roboticmachine', 'physics', 'definition', 'identifie', 'linus', 'ee', 'outsystem', 'standardization', 'advance', 'automation', 'regurarly', 'pontianak', 'roadmap', 'good', 'securitycyber', 'preprocessor', 'stepbystep', 'cciso', 'fetch', 'itil', 'confidence', 'destruction', 'scoringgive', 'webenable', 'related', 'tuning', 'box', 'cileungsi', 'accomplish', 'figmafigjam', 'router', 'department', 'understanding', 'graduation', 'discussion', 'welltested', 'socialization', 'preemployment', 'conceptual', 'aix', 'warehousing', 'sport', 'program assign', 'staff', 'penetration', 'visual', 'cordova', 'attention', 'bekerja', 'easily', 'veeam', 'mirror', 'threat', 'systemapplicationprogram', 'adaptable', 'role', 'jl', 'reference', 'welcome', 'respond', 'extensive', 'pig', 'count', 'stable', 'Gresik', 'submit', 'seo', 'meet', 'inform', 'lowlevel', 'competitor', 'leave', 'option', 'resultoriente', 'wib', 'job', 'valuable', 'city', 'infor', 'gsec', 'peripheral', 'issuesrisk', 'systemsapplicationssolution', 'consultancy', 'repository', 'mentorship', 'technologie', 'modification', 'client', 'passion', 'skill', 'permit', 'prevention', 'senior', 'check', 'list', 'expert', 'optimal', 'certificate', 'puri', 'honest', 'organize', 'ecpect', 'bottleneck', 'tebet', 'followup', 'educational', 'overcome', 'need', 'doable', 'controlleraccess', 'multi', 'tanah', 'sprint', 'budget', 'variable', 'structure', 'manual', 'traned', 'computer', 'put', 'executing', 'townhall', 'similar', 'maker', 'heart', 'outward', 'alv', 'pim', 'serpong', 'error', 'loading', 'enduser', 'undertake', 'technologyengineere', 'detailoriente', 'tracking', 'componentbase', 'deliverable', 'sale', 'situat', 'predictive', 'object', 'available', 'partner', 'leader', 'xp', 'esxi', 'seminar', 'oversee', 'curious', 'principal', 'draftdevelop', 'gapok', 'versione', 'wellformatted', 'mercurial', 'deck', 'natural', 'testrail', 'cisspcisacism', 'fulltime', 'memcache', 'upgrade', 'suit', 'willingly', 'graduateminimum', 'coach', 'holiday', 'radius', 'not', 'collaborative', 'bank', 'managementinformation', 'speaking', 'information', 'soft', 'energy', 'communicating', 'unique', 'currently', 'european', 'applicant', 'sensitive', 'gpa', 'antimoney', 'thorough', 'tradeoff', 'receive', 'quickly', 'normalization', 'digital', 'simper', 'prospective', 'ablity', 'endure', 'unauthorized', 'finance', 'transfer', 'subject', 'bwhana', 'highlight', 'systemsinformation', 'activityexercise', 'serversamba', 'competency', 'verify', 'height', 'sqloracletibero', 'running', 'formal', 'rhel', 'clear', 'creatingmodifye', 'dedicated', 'enablement', 'asyncsync', 'associate', 'zone', 'location', 'itprograms', 'breakdown', 'computerlaptop', 'salatiga', 'make', 'transformation', 'leverage', 'hvac', 'door', 'license', 'selenium', 'alibaba', 'mustache', 'vapt', 'university', 'hostkingcomau', 'persistent', 'omnichannel', 'waf', 'reproduce', 'conditioner', 'power', 'terminology', 'cibitung', 'mining', 'mvvm', 'operating', 'selfdirecte', 'incremental', 'finetune', 'monkey', 'redesign', 'supervisory', 'call', 'insurance', 'smaster', 'po', 'selfmotivated', 'microprofile', 'outofthebox', 'preferably', 'systemizer', 'placement', 'case', 'instance', 'mobility', 'strike', 'scm', 'depo', 'structured', 'brief', 'perspective', 'simultaneously', 'cross', 'fulfil', 'regulation', 'iterateagencycom', 'sciencerelate', 'version', 'total', 'dictionary ', 'team', 'processing', 'customization', 'ontime', 'especially', 'issuance', 'building', 'employee', 'fastpaced', 'obfuscation', 'effective', 'datum', 'engagement', 'provide', 'dadap', 'exit', 'wave', 'watson', 'attendance', 'centos', 'lenovo', 'assignment', 'payment', 'type', 'laptop', 'certify', 'audience', 'personnel', 'diverse', 'complaint', 'completion', 'dialog', 'shoot', 'motivation', 'sd', 'bb', 'sit', 'administrative', 'gdpr', 'plus', 'look', 'aw', 'performance', 'wireless', 'syn', 'htmlcss', 'material', 'final', 'minute', 'honor', 'detailed', 'systemsindustrial', 'enforce', 'wah', 'mlci', 'core', 'liase', 'capable', 'inventory', 'sign', 'maximize', 'salary', 'gap', 'magazine', 'sheetsexcel', 'realization', 'accountability', 'tester', 'hadoop', 'netmvcclassic', 'organizational', 'profit', 'duration', 'babel', 'failure', 'competent', 'landscape', 'enjoy', 'learning', 'exist', 'disk', 'driver', 'nonformal', 'recommend', 'conducting', 'tender', 'highperformance', 'youtube', 'nongsa', 'minded', 'epm', 'admanager', 'inbound', 'fluently', 'low', 'person', 'mapping', 'experienced', 'kmp', 'versioning', 'servicing', 'attitude', 'love', 'bash', 'play', 'mobileweb', 'xdr', 'correction', 'join', 'adonet', 'competence', 'thoughtful', 'datadriven', 'workload', 'pluss', 'follow', 'smk', 'date', 'hubs', 'newmodify', 'degree', 'declare', 'internal', 'cost', 'ransomware', 'musthave', 'local', 'elastic', 'idea', 'user', 'relocate', 'semester', 'logic', 'different', 'expo', 'upgradingreplace', 'depth', 'ndr', 'fintech', 'qlik', 'limited', 'httpseigeradventurecom', 'responsive', 'cycle', 'actuarial', 'lifeateigerindo', 'objectoriente', 'interior', 'pure', 'anomalous', 'emerge', 'policy', 'initiative', 'ivr', 'newly', 'apmc', 'par', 'txt', 'pitch', 'successful', 'face', 'mulesoft', 'primarily', 'transform', 'qsa', 'smart', 'hci', 'nhibernate', 'context', 'bapis', 'beneficial', 'guidance', 'evaluate', 'familiar', 'devise', 'sulawesi', 'sm', 'debug', 'selfdiscipline', 'interact', 'scope', 'construction', 'sertifikasi', 'testable', 'pressure', 'demonstration', 'handling', 'apium', 'candidate', 'periodically', 'incoming', 'fine', 'demeanor', 'vulnerability', 'wellarchitecte', 'summarize', 'thoroughness', 'connectivity', 'possess', 'surabaya', 'hpe', 'dell', 'alwayson', 'telemicrosoft', 'status', 'mature', 'centerserver', 'institution', 'taking', 'systemsvisual', 'calculation', 'smudiplomas', 'proud', 'explore', 'partners', 'proficiency', 'distribute', 'ensure', 'nimble', 'multimedia', 'chart', 'firm', 'practice', 'advantage', 'fee', 'group', 'organization', 'age', 'junior', 'compliance', 'star', 'programsapplication', 'tandem', 'networkserversystem', 'suse', 'livewire', 'professional', 'bpm', 'compliant', 'departmental', 'reasoning', 'indicate', 'forecast', 'bring', 'preprocesse', 'term', 'ethic', 'generate', 'progress', 'crossfunctional', 'pt', 'program', 'saturday', 'position', 'timely', 'utp', 'smoke', 'factory', 'accountable', 'airflow', 'extraction', 'jointer', 'demo', 'composer', 'afterhour', 'blade', 'incident', 'proper', 'navigation', 'individually', 'minimum', 'associatediploma', 'proactively', 'deep', 'alternative', 'indexing', 'combination', 'grogol', 'story', 'candoattitude', 'enthusiasm', 'complexity', 'style', 'bpr', 'section', 'continually', 'corporate', 'improvement', 'critically', 'ds', 'qa', 'judgement', 'international', 'ppt', 'state', 'ac', 'bonus', 'variant', 'enthusiast', 'internasional', 'change', 'agilescrum', 'size', 'manualauto', 'malefemale', 'confluence', 'shift', 'influxcom', 'outbound', 'mondayfriday', 'trip', 'siakad', 'iac', 'activity', 'readable', 'sciences', 'working', 'pay', 'task', 'execution', 'pride', 'ecosystem', 'ec', 'account', 'installationuninstallation', 'members', 'pengalaman', 'morowali', 'select', 'dialogue', 'crane', 'handy', 'largely', 'satisfy', 'furniture', 'independent', 'adapt', 'opportunity', 'conclusion', 'direction', 'lambda', 'instal', 'orientation', 'nurture', 'land', 'center', 'safeguard', 'adjust', 'wazuh', 'cpm', 'infomatic', 'integration', 'note', 'prioritize', 'talky', 'soon', 'entire', 'read', 'powerpoint', 'klapanunggal', 'email', 'channel', 'migration', 'surrounding', 'firstlevel', 'alarm', 'remediate', 'traditional', 'gunung', 'flow', 'accordingly', 'remain', 'learner', 'om', 'gms', 'trainer', 'documentation', 'sast', 'bintaro', 'hold', 'wellteste', 'clean', 'productrelate', 'continuous', 'endtoend', 'usual', 'nonsupervisor', 'snsprincipalob', 'firewall', 'largescale', 'zimbra', 'reader', 'connection', 'comfort', 'decisionmake', 'board', 'lippo', 'individual', 'measure', 'prior', 'coverage', 'enthusiastic', 'fluency', 'price', 'refine', 'prove', 'uifrontend', 'sebagai', 'kerjamu', 'remuneration', 'live', 'consolidated', 'involvement', 'antivirus', 'laundering', 'index', 'confer', 'wood', 'simulate', 'assign', 'skillswhat', 'satisfaction', 'website', 'degreemaster', 'predict', 'procedure', 'terraform', 'll', 'model', 'ide', 'lean', 'action', 'banten', 'isp', 'switch', 'digitalization', 'rounded', 'drawing', 'bawah', 'navision', 'plan', 'tenure', 'promotion', 'machine', 'smoothly', 'describe', 'ricefw', 'notice', 'pm', 'smooth', 'yang', 'create', 'retail', 'load', 'convert', 'meticulous', 'module', 'early', 'site', 'establish', 'investigation', 'nutanix', 'suitability', 'innovate', 'party', 'participate', 'iam', 'ecmascript', 'bokeh', 'previous', 'like', 'sma', 'collection', 'bitbucket', 'eu', 'foster', 'access', 'capital', 'ht', 'showcase', 'package', 'owner', 'gad', 'effort', 'assurancequality', 'pcidss', 'launch', 'evolve', 'restriction', 'additional', 'operation', 'fresh', 'refactore', 'cimahi', 'printer', 'dive', 'guarantee', 'member', 'di', 'exist write', 'knowledge', 'format', 'informative', 'proof', 'necessary', 'polytechnic', 'advisor', 'relation', 'region', 'inpatient', 'mtcwe', 'national', 'andor', 'spirit', 'bachelors', 'rich', 'comprehensive', 'apakah', 'seeder', 'onsite', 'valid', 'reflect', 'closure', 'area', 'ba', 'overtime', 'applicable', 'progressive', 'pent', 'industrialfactory', 'sure', 'period', 'internetlan', 'rack', 'virtualize', 'ido', 'etl', 'contain', 'daily', 'ip', 'controlqc', 'selfmanage', 'leadership', 'scenario', 'passionate', 'contractor', 'pattern', 'imputation', 'pp', 'deploy', 'firstline', 'initiate', 'integrate', 'tensor', 'consumption', 'welldocumented', 'cable', 'legacy', 'notation', 'move', 'capability', 'asp', 'moderate', 'ix', 'indonesian', 'carefully', 'audits', 'convey', 'sfa', 'sensitivity', 'selfmotivate', 'enterprisescale', 'outcomes', 'crossbrowser', 'innovation', 'characteristic', 'dwh', 'negotiate', 'easy', 'highavailability', 'thesis', 'preventive', 'positive', 'thirst', 'dashboard', 'line', 'minimize', 'release', 'go', 'lsmw', 'oa', 'folder', 'acceptance', 'validate', 'ciso', 'vulnerabilitie', 'hmtl', 'medium', 'strong', 'automate', 'openmindedness', 'opening', 'secure', 'ems', 'air', 'find', 'precise', 'bulanan', 'softwaretechnical', 'katalon', 'process', 'ingestion', 'zero', 'support', 'extrahoop', 'conception', 'supervise', 'consumer', 'place', 'east', 'alignment', 'berapa', 'interview', 'selfimprovement', 'interpersonal', 'diligent', 'replicate', 'infrastructureapplication', 'asynchronous', 'achieve', 'interface', 'honeywell', 'specification', 'max', 'iterative', 'write', 'late', 'mechatronic', 'agoraagencycomau', 'classify', 'evaluation', 'fico', 'deadlineoriente', 'tracker', 'miro', 'harden', 'expectation', 'grasp', 'backbone', 'sponsor', 'exceptional', 'director', 'accurately', 'increasingly', 'west', 'glad', 'ambiguity', 'spare', 'collaboratively', 'analyse', 'feedback', 'cv', 'hyperconverge', 'vsan', 'hard', 'minimal', 'timeline', 'able', 'specifically', 'sample', 'pax', 'head thr', 'batch', 'wellpresente', 'correlation', 'consultants', 'spectrum', 'research', 'mvc', 'hikvision', 'travel', 'feasibility', 'teamwork', 'scalability', 'communicate', 'entry', 'bidw', 'conflict', 'skilled', 'th', 'bachelorsmaster', 'advanced', 'gaji', 'videotron', 'interactive', 'alongside', 'detect', 'buildimprove', 'red', 'discount', 'halfday', 'needed', 'heat', 'indonesia', 'level', 'requestinitiative', 'ie', 'relevant', 'coworker', 'stay', 'implement', 'strategy', 'angular', 'assurance', 'pension', 'tbk', 'tm', 'confidentiality', 'talented', 'commerce', 'experience', 'resource', 'nvr', 'vocational', 'lesssass', 'javascriptjquery', 'transact', 'character', 'obtain', 'define', 'eager', 'scanner', 'selesaikan', 'mm', 'ansible', 'customer', 'roll', 'dynamic', 'focus', 'geographic', 'mandatory', 'walkthrough', 'assessor', 'awareness', 'reusable', 'filer', 'mastering', 'complex', 'sector', 'insight', 'hipaa', 'responsible', 'maximum', 'uncertain', 'employer', 'sla', 'retrieval', 'innovative', 'carry', 'study', 'quarterly', 'batuumbu', 'responsibility', 'historical', 'stack', 'password', 'solutionoriented', 'trust', 'infrastructure', 'engineeringcomputer', 'verbalwritten', 'ecm', 'baan', 'completely', 'custom', 'effectivenessefficiencie', 'average', 'privacy', 'determine', 'streamline', 'content', 'update', 'enhancement', 'companywide', 'selfstudy', 'record', 'cloudera', 'limit', 'methodologyframework', 'reduce', 'exploration', 'thingl. organization', 'woker', 'aml', 'clarify', 'procurement', 'crestrongenesys', 'configuration', 'act', 'raya', 'hospital', 'outstanding', 'svn', 'sio', 'pipeline', 'suitable', 'quicklearner', 'senri', 'online', 'suggest', 'noc', 'bpmn', 'alert', 'arrangement', 'worker', 'advisory', 'df', 'nonfunctional', 'selfmotivation', 'tutorial', 'projectproduct', 'xamarin', 'scala', 'ecs', 'meruya', 'studio', 'people', 'iii', 'demos', 'commercial', 'healthy', 'synchronize', 'behavior', 'clientface', 'division', 'tahun', 'hardworke', 'encryption', 'cast', 'redundancy', 'solve', 'making', 'visualization', 'run', 'outside', 'industrial', 'bonuse', 'berpengalaman', 'fund', 'korean', 'ccnahcnamtcna', 'modular', 'competencie', 'defectfree', 'eye', 'female', 'ini', 'mentor', 'manhoursmanday', 'fe', 'containerisation', 'cis', 'main', 'answer', 'stakeholder', 'boot', 'resourceusual', 'screen', 'usersrecipient', 'securityconscious', 'reputable', 'contract', 'linear', 'solar', 'manually', 'testingqa', 'bachelor', 'safe', 'assess', 'tabluqlkiview', 'breach', 'maintainability', 'physical', 'life', 'kapuk', 'applincant', 'annual', 'special', 'up', 'checking', 'benefit', 'schooldiplomabachelor', 'loyalty', 'pic', 'informatica', 'icfr', 'poss', 'sytem', 'journey', 'presto', 'equipment', 'certificatin', 'citizen', 'postition', 'writing', 'extract', 'datastore', 'criterion', 'stably', 'intuitive', 'elasticsearch', 'integrity', 'cnc', 'radd', 'agreement', 'locate', 'productivity', 'environment', 'diploma', 'xx', 'decision', 'scienceelectrical', 'dr', 'south', 'functional', 'subversion', 'outsource', 'point', 'attach', 'itsm', 'registry', 'real', 'identification', 'findingmaintenance', 'input', 'resolution', 'mentality', 'tkj', 'include', 'concept', 'lead', 'aspectsfeature', 'fastpace', 'socket', 'technical', 'operational', 'systemscomputer', 'sim', 'credential', 'base', 'relationshipsnetwork', 'shopify', 'success', 'central', 'knowledgeable', 'represent', 'waste', 'transaction', 'optimally', 'diligence', 'etc', 'encounter', 'continue', 'technologycomputer', 'npm', 'broadcaster', 'child', 'hour', 'target', 'demand', 'formula', 'take', 'optimizer', 'frequently', 'guide', 'exc

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
df_process

,descriptions,subcategory,string_length,word_count,unique_word_ratio,result_descriptions
0,bachelors degree in computer science engineeri...,Developer/Programmer,1296.0,181,0.679558,science engineering app development develop mi...
1,develop new user interface features that meet ...,Engineering - Software,931.0,138,0.797101,develop uiux design web design design backend ...
2,deeply engaged in the full development lifecyc...,Developer/Programmer,2395.0,318,0.694969,engage development lifecycle design develop te...
3,minimum working experience years passion for p...,Engineering - Software,3266.0,463,0.466523,programming programming js php mysql nosql res...
4,malefemale max age years bachelors degree in i...,Engineering - Software,344.0,49,0.938776,informatics engineer python programming progra...
...,...,...,...,...,...,...
2335,role descriptions salary insights tools to he...,Network & System Administration,70.0,11,1.000000,
2336,whats your expected monthly basic salary how m...,Business/System Analyst,232.0,37,0.783784,analyst programming sql query
2337,coordinating with team members in order to ide...,Engineering - Hardware,2118.0,287,0.679443,troubleshoot device server maintenance install...
2338,whats your expected monthly basic salary which...,Network & System Administration,593.0,97,0.546392,microsoft administrator office software admini...
2339,to do risk identification measurement monitori...,Security,1661.0,238,0.663866,monitoring control repair management security ...

In [15]:
# Analisis Panjang String
df_process['string_length_00'] = df_process['result_descriptions'].str.len()
length_mean = df_process['string_length_00'].mean()
length_std = df_process['string_length_00'].std()
length_outliers = df_process[(df_process['string_length_00'] > length_mean + 2*length_std) | 
                     (df_process['string_length_00'] < length_mean - 2*length_std)]

print("Outliers berdasarkan panjang string:")
print(length_outliers[['result_descriptions', 'string_length_00']])

Outliers berdasarkan panjang string:
                                    result_descriptions  string_length_00
2     engage development lifecycle design develop te...               641
3     programming programming js php mysql nosql res...               714
6     scienceinformation web programming web program...               491
9     programming netbean sql oracle sql server java...              1053
23    education engineering web developer tsql mysql...               532
...                                                 ...               ...
2186  server engineering scienceinformation manage s...               546
2218  server engineering scienceinformation manage s...               546
2250  server engineering scienceinformation manage s...               546
2282  server engineering scienceinformation manage s...               546
2314  server engineering scienceinformation manage s...               546

[104 rows x 2 columns]

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
# Analisis Frekuensi Kata
def word_count(text):
    return len(str(text).split())

df_process['word_count_00'] = df_process['result_descriptions'].apply(word_count)
word_count_mean = df_process['word_count_00'].mean()
word_count_std = df_process['word_count_00'].std()
word_count_outliers = df_process[(df_process['word_count_00'] > word_count_mean + 2*word_count_std) | 
                         (df_process['word_count_00'] < word_count_mean - 2*word_count_std)]

print("\nOutliers berdasarkan jumlah kata:")
print(word_count_outliers[['result_descriptions', 'word_count_00']])

Outliers berdasarkan jumlah kata:
                                    result_descriptions  word_count_00
2     engage development lifecycle design develop te...             78
3     programming programming js php mysql nosql res...             94
6     scienceinformation web programming web program...             62
9     programming netbean sql oracle sql server java...            134
23    education engineering web developer tsql mysql...             67
...                                                 ...            ...
2186  server engineering scienceinformation manage s...             61
2218  server engineering scienceinformation manage s...             61
2250  server engineering scienceinformation manage s...             61
2282  server engineering scienceinformation manage s...             61
2314  server engineering scienceinformation manage s...             61

[91 rows x 2 columns]

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [17]:
# Analisis Kata Unik
def unique_word_ratio(text):
    words = str(text).lower().split()
    return len(set(words)) / len(words) if len(words) > 0 else 0

df_process['unique_word_ratio_00'] = df_process['result_descriptions'].apply(unique_word_ratio)
unique_ratio_mean = df_process['unique_word_ratio_00'].mean()
unique_ratio_std = df_process['unique_word_ratio_00'].std()
unique_ratio_outliers = df_process[(df_process['unique_word_ratio_00'] > unique_ratio_mean + 2*unique_ratio_std) | 
                           (df_process['unique_word_ratio_00'] < unique_ratio_mean - 2*unique_ratio_std)]

print("\nOutliers berdasarkan rasio kata unik:")
print(unique_ratio_outliers[['result_descriptions', 'unique_word_ratio_00']])

Outliers berdasarkan rasio kata unik:
     result_descriptions  unique_word_ratio_00
34                                         0.0
45                                         0.0
146                                        0.0
148                                        0.0
156                                        0.0
...                  ...                   ...
2303                                       0.0
2319                                       0.0
2321                                       0.0
2325                                       0.0
2335                                       0.0

[261 rows x 2 columns]

C:\Users\HP\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
df_process

,descriptions,subcategory,string_length,word_count,unique_word_ratio,result_descriptions,string_length_00,word_count_00,unique_word_ratio_00
0,bachelors degree in computer science engineeri...,Developer/Programmer,1296.0,181,0.679558,science engineering app development develop mi...,249,30,0.500000
1,develop new user interface features that meet ...,Engineering - Software,931.0,138,0.797101,develop uiux design web design design backend ...,168,25,0.680000
2,deeply engaged in the full development lifecyc...,Developer/Programmer,2395.0,318,0.694969,engage development lifecycle design develop te...,641,78,0.602564
3,minimum working experience years passion for p...,Engineering - Software,3266.0,463,0.466523,programming programming js php mysql nosql res...,714,94,0.361702
4,malefemale max age years bachelors degree in i...,Engineering - Software,344.0,49,0.938776,informatics engineer python programming progra...,84,9,0.777778
...,...,...,...,...,...,...,...,...,...
2335,role descriptions salary insights tools to he...,Network & System Administration,70.0,11,1.000000,,0,0,0.000000
2336,whats your expected monthly basic salary how m...,Business/System Analyst,232.0,37,0.783784,analyst programming sql query,29,4,1.000000
2337,coordinating with team members in order to ide...,Engineering - Hardware,2118.0,287,0.679443,troubleshoot device server maintenance install...,365,41,0.634146
2338,whats your expected monthly basic salary which...,Network & System Administration,593.0,97,0.546392,microsoft administrator office software admini...,60,6,0.666667
2339,to do risk identification measurement monitori...,Security,1661.0,238,0.663866,monitoring control repair management security ...,237,28,0.714286

Lanjutan Penanganan Outlier

In [20]:
df_before = df_process[['descriptions', 'string_length', 'word_count', 'unique_word_ratio']]
df_after = df_process[['result_descriptions', 'string_length_00', 'word_count_00', 'unique_word_ratio_00']]

In [21]:
df_before

,descriptions,string_length,word_count,unique_word_ratio
0,bachelors degree in computer science engineeri...,1296.0,181,0.679558
1,develop new user interface features that meet ...,931.0,138,0.797101
2,deeply engaged in the full development lifecyc...,2395.0,318,0.694969
3,minimum working experience years passion for p...,3266.0,463,0.466523
4,malefemale max age years bachelors degree in i...,344.0,49,0.938776
...,...,...,...,...
2335,role descriptions salary insights tools to he...,70.0,11,1.000000
2336,whats your expected monthly basic salary how m...,232.0,37,0.783784
2337,coordinating with team members in order to ide...,2118.0,287,0.679443
2338,whats your expected monthly basic salary which...,593.0,97,0.546392
2339,to do risk identification measurement monitori...,1661.0,238,0.663866

In [22]:
df_after

,result_descriptions,string_length_00,word_count_00,unique_word_ratio_00
0,science engineering app development develop mi...,249,30,0.500000
1,develop uiux design web design design backend ...,168,25,0.680000
2,engage development lifecycle design develop te...,641,78,0.602564
3,programming programming js php mysql nosql res...,714,94,0.361702
4,informatics engineer python programming progra...,84,9,0.777778
...,...,...,...,...
2335,,0,0,0.000000
2336,analyst programming sql query,29,4,1.000000
2337,troubleshoot device server maintenance install...,365,41,0.634146
2338,microsoft administrator office software admini...,60,6,0.666667
2339,monitoring control repair management security ...,237,28,0.714286

In [24]:
df_compare = df_process[['descriptions', 'result_descriptions']]
df_compare

,descriptions,result_descriptions
0,bachelors degree in computer science engineeri...,science engineering app development develop mi...
1,develop new user interface features that meet ...,develop uiux design web design design backend ...
2,deeply engaged in the full development lifecyc...,engage development lifecycle design develop te...
3,minimum working experience years passion for p...,programming programming js php mysql nosql res...
4,malefemale max age years bachelors degree in i...,informatics engineer python programming progra...
...,...,...
2335,role descriptions salary insights tools to he...,
2336,whats your expected monthly basic salary how m...,analyst programming sql query
2337,coordinating with team members in order to ide...,troubleshoot device server maintenance install...
2338,whats your expected monthly basic salary which...,microsoft administrator office software admini...
2339,to do risk identification measurement monitori...,monitoring control repair management security ...

7) Seleksi Fitur

In [19]:
# Memilih fitur dan label untuk pemodelan
df_selected = df_process[['subcategory', 'result_descriptions']]

In [20]:
df_selected

,subcategory,result_descriptions
0,Developer/Programmer,science engineering app development develop mi...
1,Engineering - Software,develop uiux design web design design backend ...
2,Developer/Programmer,engage development lifecycle design develop te...
3,Engineering - Software,programming programming js php mysql nosql res...
4,Engineering - Software,informatics engineer python programming progra...
...,...,...
2335,Network & System Administration,
2336,Business/System Analyst,analyst programming sql query
2337,Engineering - Hardware,troubleshoot device server maintenance install...
2338,Network & System Administration,microsoft administrator office software admini...
2339,Security,monitoring control repair management security ...

In [21]:
# Menyimpan dataset yang sudah diubah
#df_selected.to_csv("bahan/final bahan/result data prep (01).csv", index=False)